### ISSUE TITLE
Doubt about Game Boy and RPi voltage level

### ISSUE THREAD

**Issue by Guillem96** [0xen/PICO-GB#1]
The Game Boy runs at 5V while RPi GPIO pins runs at 3.3v right?

Are you using any kind of level shifter to workaround this?

Thank you for your work and for this amazing project!

**Comment by Guillem96** [comment]
Never mind I successfully reproduced your results!

Thanks!

**Comment by VoxelTek** [comment]
I'm also curious regarding this. Given that the Pico would be outputting logic levels that are 3.3v to a device that expects 5v levels, would this possibly risk reliability, stability, and/or other issues? Additionally, would having the 5v logic outputs from the GameBoy going into a 3.3v device risk causing damage to the chip?

**Comment by VoxelTek** [comment]
The designed PCB seems to use level shifters, but in the image shown the lines are going direct. Has this been problematic in experience or caused any issues?
